In [1]:
import pandas as pd

In [2]:
datapath = "../data/processed/"
df = pd.read_csv(datapath + "ratings_clean.csv")

In [3]:
df

,userId,movieId,rating,title,genres
0,0,0,4.0,Toy Story (1995),"Adventure, Animation, Children, Comedy, Fantasy"
1,0,1,4.0,Grumpier Old Men (1995),"Comedy, Romance"
2,0,2,4.0,Heat (1995),"Action, Crime, Thriller"
3,0,3,5.0,Seven (a.k.a. Se7en) (1995),"Mystery, Thriller"
4,0,4,5.0,"Usual Suspects, The (1995)","Crime, Mystery, Thriller"
...,...,...,...,...,...
100831,609,3120,4.0,Split (2017),"Drama, Horror, Thriller"
100832,609,2035,5.0,John Wick: Chapter Two (2017),"Action, Crime, Thriller"
100833,609,3121,5.0,Get Out (2017),Horror
100834,609,1392,5.0,Logan (2017),"Action, Sci-Fi"
100835,609,2873,3.0,The Fate of the Furious (2017),"Action, Crime, Drama, Thriller"

In [4]:
df.describe()

              userId        movieId         rating
count  100836.000000  100836.000000  100836.000000
mean      325.127564    1855.988248       3.501557
std       182.618491    2000.247662       1.042529
min         0.000000       0.000000       0.500000
25%       176.000000     461.000000       3.000000
50%       324.000000    1134.000000       3.500000
75%       476.000000    2510.000000       4.000000
max       609.000000    9723.000000       5.000000

In [5]:
df['userId'].value_counts()

userId
413    2698
598    2478
473    2108
447    1864
273    1346
       ...
441      20
568      20
319      20
575      20
52       20
Name: count, Length: 610, dtype: int64

In [6]:
df['movieId'].value_counts()

movieId
20      329
232     317
16      307
34      279
166     278
       ...
6825      1
6826      1
857       1
6829      1
9723      1
Name: count, Length: 9724, dtype: int64

In [7]:
df.columns

Index(['userId', 'movieId', 'rating', 'title', 'genres'], dtype='object')